const FILE_DEFS = "js/file_defs.js";
const FAVICON = "media/favicon.ico";
const BACKGROUND_GIF = "media/background.gif";
const ICEBERG_JPG = "media/iceberg.jpg";
const BANNER = "media/banner.png";
const ICEBERG_CACHED = "media/iceberg_cached.jpg";
const PIN_CLICKED = "media/pins/pin_clicked.png";
const PIN_0 = "media/pins/pin_0.png";
const PIN_1 = "media/pins/pin_1.png";
const PIN_2 = "media/pins/pin_2.png";
const PIN_3 = "media/pins/pin_3.png";
const PIN_4 = "media/pins/pin_4.png";
const PIN_5 = "media/pins/pin_5.png";
const CSV = `Alberta	BBerta	0	https://youtu.be/Lco9RRH2w10
TEDx talk	The TED Talk is in reference to a Youtube video uploaded by TEDx Talks on August 16th, 2016 with the title "Joke's On Us", in which a high-school Aspecticor in a silly looking suit attempts to present an argument in favor of humor and why it is important in daily life -- Just watch it. Go ahead. Click the link. It speaks for itself. Andrew Will is a Brentwood student hailing from Red Deer, Alberta. He has many interests here at the school, ranging from musical theatre to debate. He is also a dedicated member of the Hockey Squad, although many would describe his position not as a left-wing but more of a left-bench. Being one of 60+ plus students from Alberta, he loves the temperate climate, but misses the piles of snow and the decent hockey teams back home (The Calgary Flames).	0	https://www.youtube.com/watch?v=LuXoLoMnoww 
bisexual	Bicycle? Huh? Say it into this ear, this ear's better.	0	https://www.youtube.com/watch?v=6PgGa9NPchQ
Hitman Horse	HITMAAAAAAAAAAAAAN HORSEEEEEEEEEEEEEE	0	https://twitter.com/Linkus7/status/1579278016613490689
being short	The human equivalent of a toy poodle	0	https://media.discordapp.net/attachments/885706697228816464/1108866303634178099/sa.png?width=265&height=471
dent	Open https://i.imgur.com/t6s5STf.png on stream right now do it you wont chat dont let him not open it please i beg you please please please	0	https://clips.twitch.tv/WonderfulAbstemiousLorisItsBoshyTime-nMm5-lbllUCLHaMB
Bald	(show scalp for demonstration)	0	https://clips.twitch.tv/TrustworthyBashfulKoalaHassanChop-N9CrqI89EINLUJcr
Speedrunning	he sure is a speedrunner (although he is easily mistaken for a slowstander)	0	https://clips.twitch.tv/StrangeTallButterGingerPower-2TLIfSnr1U_VtSu3
Hardcore freelancer speedrunner	"One more run chat, I swear!"	0	https://clips.twitch.tv/ColorfulCourteousRatMikeHogu-2E8A_aJm6JZv7-kk
Partnered	Partner application took months to get accepted, Xemdo allegedly pushed it along, accepted mid-subathon	0	https://clips.twitch.tv/CalmArbitraryDugongDoggo-y7dR3BN4zO98EWmI
Subathon	as opposed to a domathon, because he is a bottom	0	https://clips.twitch.tv/BlazingLaconicButterPeteZarollTie-3cLmkgG6XdHh5Nqu
Boris	Boris Joris is the REAL name of "Aspecticor"	0	https://clips.twitch.tv/AttractiveBoxyPotDerp-YBG1kY6-hLwJcdqO
Bird%	Bird% is the Hitman speedrun that all have been raven about. You have to fly through all the maps as quickly as possible without doing anything ill-eagle while only using the blue mascot da-skies. Starting in Parrot, France, Owlspecticor must assassinate Dalia Mallardgolis by dropping a chandelier on her, quacking her skull. In Flapienza, he must ignore the birds of pray in the church and instead head underground, eliminating a dangerous bird flu. In Marrakeet, he passes the people eggs-ercising their right to protest and head inside of the Swallow consulate. In Bangkokatrice, Jordan Crane is quacked on his bird-day while Ken "The Chick" Morgan poses no threat to our fine-feathered hitman, and goes down without so much as a hoot. In Coloradodo, Sean Crows, Ezra Bird and his crow-nies go down without a flight. In Hawkaido, ICA leader Erich Sparrows gets no special tweetment and leaves Diana feeling emu-tional. -- Moving to Hawk's Bay, Alma Flynard gets pecked by a syringe and her eagle-eyed guards can't spot Owlspecticor. In Flyami, Owlspecticor eggs-ecutes Sierra Hawks as the crowd hoots and hollers. In Santa Flamingo, he puts an end to the Caw-caine production in one fowl swoop. In Magpie, India, Dawoodpecker Robin thinks he's an up and coming comedi-hen, but is sent crashing down to Earth. Penguittleton Beak might seem more serene, but Owlspecticor goes stork raven mad and eliminates his long-forgotten foster feather. He then pays a visit to the Stork Society on the Isle of Seagull, is in impeckable form as he ends the bill-ionaires. In New Yolk, Owlspecticor has the option to crash the stork market, but instead goes cheep and gives Athenosprey his season's tweetings. Across the pond in the Maldoves, Tyson Billiams is feeling under the feather and Owlspecticor makes it worse by robin him of his life. -- In Dufly, he says "beakaboo" to Carl Wingram and Marcus Storkvescent. In Larkmoor, not far from Duckingham Palace, he is presented with a case to quack, but chooses to instead go quackers on Alexa Quailisle. In Birdlin, Owlspecticor tells his pursuers that toucan play at that game, and hunts them down until he's owl by himself. In Chongkingfisher, China, he gives Emugen Royce a wound not even the best duck-tor could heal. Hendoza, his hen-ultimate location, Heron Archibald Eagle was not emu-sed by Diana and got flown up by a rubber ducky. Finally, in the Cardinal Mountains, a guard asks if they are in U-crane, but they are in fact in Crow-mania. Owlspecticor ends this saga by making The Ostrich's memory crow away. -- I hate my life	0	https://clips.twitch.tv/AdorableFunZebraCoolStoryBob-3NLczGR4A8LhXmTa
AI TTS Voices	Many AI voices have recently taken prominence on Aspect's stream. Of particular note is Gordon Ramsey, whose voice often accompanies quite profanity laiden messages.	0	https://clips.twitch.tv/AgileElatedHummingbirdBudStar-YMFm-U8oHZU8l_Yg
Catcam	Let's be honest, Mercs is the only reason most of us watch	0	https://clips.twitch.tv/FurtiveEnjoyableClipsdadKlappa-zcv0V8k3oOUrbGDF
Canada's Worst Driver	Canadian reality game show focused on rehabiltating chronic bad drivers, hosted by Canadian hearthrob Andrew Hung- *cough* Younghusband.	0	https://clips.twitch.tv/CuriousPoliteManateeCopyThis-WIGz8_Kaovnu67Xe
Nightmare mode "12 hours"	Clueless	0	https://clips.twitch.tv/MildCleverMochaFrankerZ-jdEIq1CICLnoCSH2
Canadian	For shame.	0	https://clips.twitch.tv/SweetHilariousAlligatorArgieB8-Rom4kpcWqUimnFDk
La Vaca	moo	0	https://www.youtube.com/watch?v=8jTjNMkWOzM
mods locked in basement (help)	the part about making us watch the Edmonton Oilers is especially true though, even though we'd rather have running water and blankets to protect against the frigid Canadian environment	0	https://clips.twitch.tv/SpoopyPiliablePorcupineCoolStoryBro-bfuGjzGvGSpUcs1x
WR holder	this is down a level because it's been so long that new frogs don't know he's a world record holder PepeLa	1	https://clips.twitch.tv/DoubtfulBloodySnailKeepo--qNdxMUJMNPUW3G4
Streets 1:12	I've never SEEN a 1:13, and I never fucking will!	1	https://youtu.be/oYmqJl4MoNI
SHEWS	During the subathon, couldn't beat Winnie the Pooh's Home Run Derby (there's a Ludwig vid on it) and he played Centerfield almost the whole time, plagued the subathon	1	https://www.youtube.com/watch?v=Xq3hEMUeBGQ 
TheaterBoy	In his high school years, Aspect was quite the theater boy, being featured on his schools YouTube channel with an inspiring quote about community. He can also be seen doing flips and flying around on a wire, which is the subject of the TheaterBoy emote. Years after his final act as a theater kid, Aspecticor made one final grasp at finding that glory from his olden days. Just like he had flown around on stage years earlier, Aspecticor took a rope and tied one end around a ceiling fan, and the other around his waist. However, the fan could not support his weight, and he had to be sent to the hospital from injuries sustained after the ceiling fan came crashing down on top of him.	1	https://www.youtube.com/watch?v=Ls7etcfw2iA 
"it's better to give than to recieve" clip	The most viewed Aspecticor Twitch clip, surpassing the first time he got a world record. That's the place this stream is at right now.	1	https://www.twitch.tv/aspecticor/clip/DullHelplessCarrotHeyGuys-KMUqZTSDTW50aZsb
ScriptDesk's Aspect poster	The poster is a huge fixture of the stream but have you ever looked at it closely Pog we love script	1	https://twitter.com/aspecticor/status/1484684858139938817
real voice	Aspecticor's real voice, as known to people who have met him in real life, is quite high-pitched and tinny, almost like a Canadian Mickey Mouse. It's a wonder that people tolerate his presence. Understandably, he uses a voice changer to sound more masculine to be taken seriously whenever he's on stream. At time, this voice changer breaks and for brief moments, his natural voice can be heard.	1	https://clips.twitch.tv/SweetInspiringBeanTwitchRPG-a5rHjRzbnXs8ORld
MASTER	back before he played freelancer (hardcore just doesn't have that same ring to it), he speedran SA/SO trilogy on the Master difficulty because counterintuitively, he wasn't good enough for the Professional difficulty. Unfortunately, it makes the game harder, which is a bad combination for him.	1	https://clips.twitch.tv/SingleBeautifulScallionMikeHogu-zUjq9l0A39IPnOGY
Biphobic Cat	Mercs makes a point of often attacking Aspecticor's bi flag, leading many to believe that she is in fact biphobic. When held up in front of her, she chose to attack the bi flag instead of the Flavortown flag.	1	https://clips.twitch.tv/RelievedBoldPeafowlArgieB8-M5qmTpJSCHzPR84i
Coma	IF YOU ARE READING THIS MESSAGE WE HAVE MANAGED TO SEND A MESSAGE INTO YOUR MIND AND NEED YOU TO KNOW THAT YOUR FAMILY LOVES YOU NEEDS YOU TO WAKE UP NONE OF IT IS REAL IT IS ALL IN YOUR HEAD	1	https://clips.twitch.tv/PoorDepressedAsparagusFunRun-s39XUfbs3nZO4O23
WACKASSNAILS	WACK ASS NAILS, often followed by a LULW, is a reference to the fact that Aspecticor has self-proclaimed wack ass nails. They are strangely and inexplicably short, a fact which has led to many sleepless nights and tormented days. My his own admission, it is a "great shame" he holds.	1	https://clips.twitch.tv/PlumpConsiderateYakWOOP-2nX23V6jmkeTcovz
Slurspecticor	"Slurspecticor" is a moniker given to Aspecticor in reference to his ongoing trend of saying politically incorrect and offensive statements on stream. On February 2nd, 2022, while streaming HITMAN III, Aspecticor made a shocking admission. Out of nowhere, he brazenly stated that he sometimes slurs. This clip was clipped by QornOnTheQob, therefore, they made the moniker originally. Shocked and appalled, his audience took to Twitter with the #CancelAspecticor, which reached #3 trending in Red Deer. Aspecticor ended stream and returned a day later pretending to be sad, but it wasn't very convincing when he was splashing the fake tears on his face on camera as he apologized. Eventually, following an enlightening reading of 1984, Aspecticor began to ban all mentions of a "slur incident". However, because he is lazy, he eventually gave up at this, and his fans began calling him "Slurspecticor". Further reading: https://aspecticor.fandom.com/wiki/Slurspecticor	1	https://clips.twitch.tv/OptimisticMagnificentTitanPipeHype-_xeYcE1djmEow5IR
Speedrunning PlayingHitman GoingLive WatchingStreamTogether ComputerScience Evan emotes	where would we be without these classic femboy/egirl emotes	1	https://clips.twitch.tv/EasySpeedyHamburgerLitFam-e3h0JvmhpP8xDChp
Alcoholicor	At the young age of his TEDx talk, Aspect had yet to learn a crucial factΓÇö alcohol is the real social lubricant. Since that realization, he has been chugging down liquid courage at every opportunity: on stream, off stream, on the road, you name it.	1	https://clips.twitch.tv/DeadCleverOstrichYouDontSay-sSxe7Dg_USlf5k6T
ad incentiveathon	i cant believe he's streaming for money and not the love of the game!!	1	https://clips.twitch.tv/BillowingSparklingMetalNomNom-HwCCMjeYN_xZh8II
Canadian Education	He probably wasn't even taught that Canada was annexed in 2014.	1	https://clips.twitch.tv/AstuteDeliciousSandstormMau5-JNbOnApH81nzE0W1
BKFL, Mayfield Heights	On July 16, 2012, 11:38, an image was posted to 4Chan. The photo was of a kitchen worker's feet inside two plastic bins of lettuce. The image would be traced to a Burger King in Mayfield Heights, Ohio. A chatter named "Cartwheel76" is probably already spamming the chat with "BKFL" as we speak. Let him do that, he doesn't have very long, poor guy.	1	https://cdn.7tv.app/emote/6360c19c7e05051479ea1bc4/4x.png
RefreshChatOverlayIUploadedAnotherEmote	Aspecticor's stream chat overlay has the unfortunate feature of not being able to refresh in real time as an emote is added, as the mods are wont to do. This leaves a very funny emote, in the form of a picture or video, being unable to render on screen and just be another word. Because we cannot have stream be reduced to what the mobile users basically see on a daily basis, we require that the chat overlay be refreshed posthaste.	1	https://cdn.7tv.app/emote/60b1657f81bdd27f2b44fd0d/4x.webp
Strange flag	Some sort of sideways French flag, weird sexuality tbh	1	https://i.imgur.com/Yw5Rtkb.png
January 6th	There are reports of Aspect being seen at the January 6th riots	1	https://media.discordapp.net/attachments/264217465305825281/1128246509679419452/image.png?width=834&height=471
Amok Runner	Excuse me... SCHIZO I think you wanted to sit alone SCHIZO because when you saw me SCHIZO I had the feeling that you were a bit hesitant. SCHIZO Please stay. SCHIZO I'll leave. SCHIZO You don't bother me. SCHIZO On the contrary. SCHIZO I am glad that I am not alone once in a while. SCHIZO I haven't said a word to anyone for ten days. time to go	1	https://clips.twitch.tv/IntelligentBitterDuckBabyRage-Mnw5q2IMYGMhX7Ag
!comment	once disabled it after chat and aspect got fed up with braindead commenters not understanding speedrunning.	1	https://cdn.7tv.app/emote/637abe43c1fffda310081ea4/4x.webp
Cal Kestis	self-explanatory	1	https://static.tvtropes.org/pmwiki/pub/images/cal_kestis_sw_1.png
Chatter Food emotes	who are these self-important individuals who think they deserve their own personal emote huh how dare they make me hungry at 5 am fuck	1	https://i.imgur.com/8bgznxP.png
Red Deer	What the fuck even is a red deer? Look it up. They're literally brown. Anyway, this is Aspect's hometown.	1	https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Red_Deer_-_Aerial_-_downtown_bridges.jpg/263px-Red_Deer_-_Aerial_-_downtown_bridges.jpg
aspectibot/botspecticor	totally not sentient beings	1	https://cdn.7tv.app/emote/609ef3684c18609a1d9a615d/4x.webp
hey did you guys know he climbs?	type AspectiClimb in chat	1	https://twitter.com/aspecticor/status/1652733375134965762
Dog Suit	A polarizing suit, it is one of the options the wheel of punishments can land on during Freelancer Nightmare mode.	1	https://i.imgur.com/eazNDIt.png
aspect ratio	Aspecticor can be such a dunkable guy, but no aspect ratio can fit all the Ls he takes on stream gottem	1	https://media.discordapp.net/attachments/938997969036910652/1128203089439101048/image.png
scuffed OBS	no dual audio Sadge	1	https://i.imgur.com/TPfo1OS.png
partner (KatieGray emote)	KatieGrayx3 insisted we add this, we did eventually so guess she won	1	https://clips.twitch.tv/UgliestGiftedFerretPRChase-YJpM3nkROSfzYCoh
Onlyfans	REMEMBER HE PROMISED ONLYFANS AT 1000 SUBS MAJ	1	https://clips.twitch.tv/SecretiveNurturingSheepGingerPower-rrErOqO0t_qoNtvx
Diana Cosplay	humina humina	1	https://clips.twitch.tv/NimbleBlightedGarlicSSSsss-Oe7ZMh3uwG4-KG_x
Linda	Character in Moist Speedrun Comp game "Amok Runner", RIP	1	https://clips.twitch.tv/IntelligentBitterDuckBabyRage-Mnw5q2IMYGMhX7Ag
Katie (cousin/girlfriend)	They were made for each other as soon as they met at their second family reunion	1	https://clips.twitch.tv/GenerousOddApeHassanChop-ZLa2dkaq7sXfuxqf
show hog	WARNING: DO NOT PLAY ON STREAM, NSFW CONTENT!!! Aspecticor once promised to show hog if he threw a run (which he did, of course) and he made sure that Twitch staff weren't around and did a little quick reveal. Luckily for him, the people at Twitch were too busy laughing at  his misshapen hog to ban him. Chat keeps asking him to show hog to this day, and he obliges sometimes.	1	https://clips.twitch.tv/DiligentDiligentButterTBCheesePull-2HztJAUFautjrSn-
MostButNotAll	At the start of the Whittleton Creek, the line "Most, but not all" is said in reference to most of the town residents being regular suburban people, but some being members of secret organizations. This emote depicts a pie chart which is most, but not all, purple.	1	https://cdn.7tv.app/emote/6371fe95ee459cc2ae706979/4x.webp
"chat being really cute"	"they should all smile more" -onteia	1	https://cdn.7tv.app/emote/631210ee113e0e8575d2d130/4x.gif
look what Onteia taught me Smoge	Onteia, for all their wholesomeness, taught people bad habits. Perhaps they're extra wholesome because of their old ways, or maybe their way to take the edge off made its way to others.	1	https://cdn.7tv.app/emote/60af8da952a13d1adb141008/4x.gif
Kick stream	His inaugural Kick stream consisted of showing his hog and then restreaming his old, better content	1	https://clips.twitch.tv/EntertainingDelightfulRaisinBudBlast-JAxKVxAWYc-FsYOX
hardly know her!!!	Long-running kneeslapper- wait! wait no!	1	https://cdn.7tv.app/emote/63d620d1f08dc45e2c7e64f8/4x.avif
union	the chatter (and moderator) union: the Associated Stream Patrons' Elected Coalition To Improve Chat, Organized Roster	1	https://cdn.7tv.app/emote/61c53b8c1cc80462ef2d0fe8/4x.avif
Streamer Awards	Nixolay's +1	1	https://twitter.com/aspecticor/status/1635757834196471809
Charity stream	The Trevor Project is cool and pog and the charity stream raised a lot of money for it ezz	1	https://clips.twitch.tv/RelentlessSoftDogEagleEye-IAh23VsN4OU8JpT7
NotLikeThis Oh No!	chat react with "NotLikeThis Oh No!" especially if he's ranting about how it's a dumb feature again	1	https://static-cdn.jtvnw.net/emoticons/v2/58765/default/dark/3.0
Coffee Cow	Based on the popular "Coffee Cow" joke from r/atrioc, Aspecticor whipped out his most successful parody song to date. Sitting at 52K views at the time of writing, it is one of the most popular leech songs, surpassing his previous most popular song "Glizzy Man," and only second to the song compilations that Atrioc himself posted, "ONE LAST HIT," and PeyTheMusician's "The Tale of the Coffee Cow." For much of its history, the video has been unlisted, like at the time of its release. When it was first made public a few days later, views skyrocketed and would only later be surpassed by his Hitman speedrun explained videos. Right now, unfortunately, like most of his other content (especially related to Atrioc), it is unlisted, despite a union motion to the contrary.	1	https://youtu.be/aSGPUf607vE
Commerce major OMEGALUL	!unsub, get a real job	1	https://i.imgur.com/ZycCsy3.png
hippie commie pinko queer	but is it true Hmmge	1	https://twitter.com/aspecticor/status/1566592789290557441
Deepinsideaspecticorsass	Back before ToxicCheeseburger was ToxicCheeseburger he was DeepInsideAspecticorsAss and before that he was deepinsideaspecticorsass and before that he was Anonymous Gifter. But he got Atrioc to say his username and for a long time the sub audio was "I am deep inside Aspecticor's ass."	2	https://clips.twitch.tv/SpicyPreciousOryxKappaRoss-OpxcVOMuX-IFQ7z6
pumpkin	A rare skin his cat Mercs occassionally equips. Aspecticor is adament that it is a friends cat, and that it isn't Mercs. Do not believe his gaslighting claims	2	https://clips.twitch.tv/HedonisticBravePangolinRalpherZ-oJ30v-zV9aB1UocR
terrible ICA facility hitman horse contract	Aspecticor didn't know how to mark targets, so he was really just set up to fail here tbh	2	https://youtube.com/shorts/v1tN-KiJcbI
old sub audio	Atrioc thought Aspecticor was an idiot for trying to go for the record when the leaderboard would just get wiped because of a new patch. This didn't end up happening, and the score stood for a while until the inevitable patch came.	2	https://www.youtube.com/watch?v=qWNadi8i3UE
Johnathan (Elusive Target)	Johnathan is the most successful musician in the universe and an icon in the Aspecticor stream community. According to his mission briefing, his first album was downloaded 50 million times in its first 3 months of release. This feat has not been accomplished since the invention of iTunes, making Johnathan the objective bad boy of music. The part that makes Johnathan near and dear to Aspecticor fans, however, is not his music, but his history of having committing a multiple homicide. Just like the streamer himself, he was never punished and even went on to create more music after. Johnathan's godly visage has inspired a number of emotes in the community, such as "Johnathan", "Nonhathan", "HYPERJOHNATHAN", "GIGAJOHNATHAN", and "JohnathanDespair". If anyone is caught using the blasphemous emote "Drake" instead of the lordly emote "Johnathan" they will be sentenced to 14 years hard labor in the Asylum.	2	https://cdn.7tv.app/emote/62ee0ce28493424b4a25b14f/4x.webp
Fartmoor :tf:	"Fartmoor" is the funniest joke ever made in Aspecticor's chat and a true miracle of wordplay. Combining Dartmoor, a map in HITMAN III, with the word "fart", Fartmoor is surely to elicit laughter wherever it appears. It is often paired with the trollface emote, to indicate the whimsical and mischievous nature of the joke.	2	https://i.imgur.com/G0VzwHe.png
!mastery	I got a couple questions one is I noticed you're on level one during the game through how is it you got all of the stuff unlocked on level one mastery?  Because I also see you The bottom right it says mastery level one of one that's on all levels you're playing i'm afraid that clearly shows a modified game file. two Can you do this on a council not just a PC? I have my doubts because you might have modified file system on your PC due to the fact that you have all of the items unlocked and you're at mastery level one. If you can do this on an Xbox series X or PS five or four I would be impressed then. Otherwise I have my doubts that's probably why Ioi Interactive don't really make big noise when people post these especially when they're on a PC.PC games can be modified Council games cannot. I'm not really interested in speed running because I like to enjoy the craftsmanship that the developers put into the game! Sort of like if going to a movie and then asking the projectionist to fast forward to the ending right away!😀 -SuperAgentman007	2	https://i.imgur.com/2jOmXe6_d.webp?maxwidth=760&fidelity=grand
Greg (lawn mowing sim)	Greg was an RCMP officer before he was disciplined after passing out drunk in a Burger King parking lot. His wife took the kids and he spent much of his money on a trip to the US Capitol in January 2021, but he tries to do his best as a humble lawn mower.	2	https://clips.twitch.tv/UnusualSneakyCucumberTwitchRPG-ZNA2AHFRbtc-ddYN
they speak African	slurspecticor at it again -- and again: https://clips.twitch.tv/ZealousToughBaconHumbleLife-F8xWmuMnLcNx7KYs -- and again: https://clips.twitch.tv/ThankfulObeseCookieNomNom-An9tnDgccHSxAqfY	2	https://clips.twitch.tv/ConsiderateSpicyShrewCoolStoryBro-ujhTzPFzn4JGAgOY
Aspecticor Wiki	A compendium of many of Aspect's early to mid streaming incidents, personas, and other random happenings. Originally started by Moksha though with contributions from other chatters such as Cartwheel. Everything on the Wiki is confirmed TRUE by real Canadian patriots.	2	https://i.imgur.com/zu9AhLt.png
Muffin Boy	Back when Aspecticor used to speedrun trilogy, he used muffin skips a lot. He also failed (Muffed) them a lot, but that's besides the point. Aspecticor used them so much, he eventually talked about them in a video that gained millions of views, with many comments talking about how crazy it was that a simple muffin was used to break the game. Naturally, IOI caught wind of this, and put an end to this tomfoolery at once, so that normal people could finally enjoy the game. At least, that's one way it happened. They say that it was an accidental patching when fixing another feature and they never intended to harm the speedrunning meta. But let's be real, that was just polite talk after Aspecticor released the hit video "The Update That Could Kill Hitman Speedrunning." And that video has a blueberry muffin right in the center of the thumbnail. What a muffin boy	2	https://cdn.7tv.app/emote/635f125d663949494fc9e7df/4x.webp
retelling the ditch story	Sure, Aspect, that woman "didn't want to go in an ambulance" and you "didn't hit her". We've heard it before	2	https://s.hdnux.com/photos/50/24/54/10570553/6/rawImage.jpg
logo rebrand	💀	2	https://static-cdn.jtvnw.net/jtv_user_pictures/4fc4760f-7844-46ec-96e5-eb0dde3c9702-channel_offline_image-1920x1080.png
Long hair	Aspecticor once had long ginger hair, reminiscent of Manny the mammoth from Ice Age. Unfortunately (or fortunately, because it's crazy he thought he could pull it off), he has a rare form of really fast male-pattern hair loss, so the long hair era is long over. The emote Aspecticles in chat is but a solemn reminder of what once was.	2	https://clips.twitch.tv/AuspiciousElegantOxOptimizePrime-17fG8gIbcNaWpivq
Uptown Funk	On July 9th, 2015, a video was uploaded by the title "Andrew W - Concert for a Summer's Eve 2015", in which the titular Andrew W, also known as Aspecticor, performs a live rendition of Bruno Mars's "Uptown Funk". All things considered, it actually isn't too bad. Unlike the TED Talk, he likely had some idea of what he was going to do more than 15 minutes before getting on stage. However, small things like the comically oversized suit and the trumpet players having an aneurysm at 2:30 turn a decent performance into a comedy masterpiece.	2	https://www.youtube.com/watch?v=v7bG3UbOXqQ 
merch	chat! did you know that Aspecticor sells merch? you did? and it's currently sold out? well bug mr. streamer to sell more merch! partake in the capitalist system! get those southeast asian child laborers on it	2	https://www.youtube.com/watch?v=E9ZMo1NQCSo
Peacock	Peacock is a custom Hitman 3 server that allows you to use every unlockable item in the game without grinding. It enables the use of AutoSplitting & has less server disconnects. To learn more, visit https://thepeacockproject.org/	2	https://www.youtube.com/shorts/b0I6wWsLxjc
aspecticor fan club at UCB	the realest of fans tbh	2	https://twitter.com/punchingwaves/status/1619931644881965056
shroomspecticor	"Shroomspecticor" is a moniker given to Aspecticor to reference the fact that he is a rampant psilocybin (magic mushrooms) addict and frequently exits stream to take more. When he goes too long without shrooms, he will start to become restless and laugh at everything. Aspecticor first revealed his shrooms addiction during a Halo Infinite Stream. Fellow Atrioc leech Syk1k confronted Aspecticor about his drug usage, asking what drugs he does. In response, Aspecticor answered "Shrooms." Nobody spoke a word for the next 15 minutes until Aspecticor broke the silence by laughing out of nowhere and then walking off stream for 5 minutes. When he came back, he acted like nothing happened. After this incident, his fans began to call him "Shroomspecticor".	2	https://static-cdn.jtvnw.net/emoticons/v2/emotesv2_6bf174b0227d4b6f972ced5a445bc105/default/dark/3.0
ASPECTICORING	Because Aspecticor somehow found success as a speedrun documentary YouTuber, he finds the incessant need to explain every little thing (somehow still chat doesn't know what an elusive target is). This is a video of him in action, unedited in any form	2	https://clips.twitch.tv/ViscousTacitCakeDuDudu-JPFV8LXUhBha-eTK
VGHS	RocketJump web series, played a lot during subathon sleep segments.	2	https://clips.twitch.tv/PricklyIncredulousRavenSuperVinlin-zx4p_stOcL1PaqYW
Elastigirl	During the subathon, he watched the Incredibles movie series, in which he consumed copious amounts of alcohol (see Alcoholicor) and ogled Elastigirl. After fulfilling a donation goal, he ordered a cardboard cutout of Elastigirl to be placed in the background of his stream. The Elastigirl cutout was very popular with chatters, with them donating gift subs in order to have their name signed on the Elastigirl cutout. Unfortunately, it was probably not as popular with the females living with Aspecticor (being his cousin and his cat). One day the Elastigirl cutout disappeared and was never seen again.	2	https://clips.twitch.tv/TubularBelovedPeachPJSalt-F4sE5LyxviY7-8u8
frosted tips	frosted nips POGGIES, you can totally see the difference, it's just the light COPIUM	2	https://clips.twitch.tv/MuddyColdCocoaShazBotstix-Q4AxIzXF_1ATXEMA
aspectiDumpy	jhort paid him to do it, eventually got removed by Twitch	2	https://clips.twitch.tv/IronicPlacidGarlicNinjaGrumpy-yYiKuPajBazxlNOf
TypicalSoyGameExploiter	This emote features a clip of Aspect's webcam taken from his attempt of the DougDoug GTA Challenge in which he has an exaggerated response to surviving a perilious situation. The name of the comment is in reference to a comment on one of Aspect's YouTube videos, calling him a "typical soy game exploiter" for using cheats in his speedrun instead of pulling himself up by his bootstraps the good ol' fashioned way. 	2	https://clips.twitch.tv/FriendlyDeliciousLorisEagleEye-GmRS8_tHVDB0nErG
subathon nightmare	He had a glimpse of his future self as a content creator, or an even scarier possibility: the present.	2	https://clips.twitch.tv/FineGleamingNuggetsBCWarrior-OgZyyPFNfDPJMtyH
JK+ Incident	Whilst playing Jump King, chatter B1ink01 made multiple attempts to get Aspect to install a mod known as JK+, which allows multiple people to play on the same map and see each other if they pass each other. On top of this, B1ink01 made no secret of his Jump King proficiency, and was ready to dust Aspect the second he installed JK+. However, he was banned instead and Aspect proceeded to rant for 14 hours about people wanting attention for things they are good at. B1ink01 may as well have been permabanned if not for mods advocating on their behalf, and now they're an oldhead of the stream.	2	
TTS Brian	Before the rise of AI and their deeper involvement in text-to-speech technology (TTS), all TTS requests were read out by Brian. Fortunately (or unfortunately) the messages were no less psychotic.	2	https://clips.twitch.tv/BlitheResourcefulPuppyMingLee-kkAgCf7KYNr0hp-K
he fell in the toilet :(	When Aspecticor leaves stream, he often takes minutes at a time. One possible explanation is that due to his miniature stature, he falls into the toilet and is spending those precious minutes off-screen climbing for his life to escape the sewers below.	2	https://cdn.7tv.app/emote/62f49438f4cbcdff572246ad/4x.webp
Fappie	it means "fast sappi" get your mind out of the gutter	2	https://cdn.7tv.app/emote/61ecda74cc9507d24fd4c962/4x.webp
Red Car	This is THE red car, the one that Sierra Knox drives in Miami, the one that Aspecticor has to shoot. But did you know it makes an appearance in the Sanguine fashion show in Paris? It's true	2	https://oyster.ignimgs.com/mediawiki/apis.ign.com/hitman-2/7/7b/A_Perfect_Machine_Cover.png
gorilla warfare in colorado	Welcome 🤝 😋 to Colorado, 47. 😪 The 🦏 🤣 militia has 💰 taken 💅 up 😱 HQ 🏫 at an 🌑 🤼 old 👴 👶 🗝 📺 apricot farm 🚜 🌽 🚜 🐓 and :tone5: 👏 appear ⁉ ‼ 🔎 to 💦 💰 be 😱 🐝 training :tone1: 🚆 🚅 🚋 for 🌹 🈺 😊 a ⏰ 🍬 series 📰 of coordinated strikes, 👏 ranging from 🅱 😤 🚥 cyber-attacks 🙅 ♂ 👊 to 💦 ✌ full-blown 💯 🌝 🌕 gorilla 🦍 🦍 🦍 warfare. 💣 💣 🔧 We never see the gorillas so they must be hiding from us. Good thing too or Aspect would put a bullet in their head, being the monster he is.	2	https://www.youtube.com/watch?v=X0-CKXuP7pc
El Tigre / Dr. Fauci	El Tigre is Aspecticor's name for his own Fall Guys bean, because of its orange and black striped pattern. Atrioc was wearing a mask to hide a terrible sore on his mouth, so instead he called him Dr. Fauci, knowing that this would turn him off from his target demographic of right-wingers and fellow Tucker Carlson watchers.	2	https://www.youtube.com/watch?v=t6bZd_wg4k8
90s kid	"you're not a 90s kid, you weren't a kid, you were a 90s fetus" -Atrioc	2	https://www.youtube.com/watch?v=t6bZd_wg4k8
aspecticor died	Atrioc graciously called Aspecticor to concede the trilogy world record,, and Aspecticor disrespected him! Of course the clown would defend his honor	2	https://www.youtube.com/watch?v=cbny1RkmIx8
hunted	Hawkes' Bay glitch that would instantly end runs	2	https://www.youtube.com/shorts/kmVpAQFgByE
Teaching HITMAN	"He also told them this parable: ΓÇ£Can the blind lead the blind? Will they not both fall into a pit? The student is not above the teacher, but everyone who is fully trained will be like their teacher."" - Luke 6:39-40	2	https://www.youtube.com/watch?v=WqmCsfqkYPM
Cuphead Stream with Silence Vids	crazy how he never did another cuphead stream again, since this was such banger content. Onteia did such a good job with this video (Yes she did Madge stop doubting yourself Onteia SoCute)	2	https://www.youtube.com/watch?v=U07mVNkfofQ
REROLL	artesian builds be like	2	https://www.youtube.com/watch?v=aR3cw7jGRvI
Molotov Cocktail	The molotov cocktail was an item that was crazy overpowered because you could set someone on fire (free SA/SO accident kill) basically anywhere out in public. It also had the feature where you could shoot a dart at it to release its fire, and then you had the normal explosive that you could pick up and use again. Unfortunately all good things must come to an end and it was nerfed in a patch that came a few months later.	2	https://www.youtube.com/shorts/sUFKPFYvH4A
Tim Danter and his crypto channel	Who wouldn't trust Canada's best high performance driving instructor with financial advice? Heading to the MOON	2	https://www.youtube.com/watch?v=Y8pSRt3PC04
Unban Forms	Back when chat was funny and Aspecticor banned people for losing marbles, he used to read unban forms as content. Eventually though, he became too lazy to do even that, as he stopped playing marbies and only racists applied for unbans. It's been months Sadge the frogs demand content	2	https://clips.twitch.tv/PlausibleFilthyAppleTheThing-FWyogdo7vc6qug1E
Misspecticor	After missing his 45th consecutive pistol shot on the stalactite above the virus in Sapienza, Aspecticor earned the moniker of "Misspecticor", commemorating his time honored tradition of inexplicably shooting everywhere and everything besides the enemies. 	2	https://clips.twitch.tv/VivaciousGloriousAntWoofer-NMi5k8FcDURTBzo0
scooby	zoinks!	2	https://clips.twitch.tv/RudeAgileBaboonTriHard-8Ey8Vkvwmd-2siBN
Atrio arc	He playtested Atrio, was in many of IstoInc's videos, played Atrio Racing with Atrioc and Linkus	2	https://clips.twitch.tv/ResilientTrappedSmoothiePRChase-DjsGuej0htqC9mcy
Cock Launch	In the game Amok Runner, there is a glitch in which one must launch themselves in a bike off of some chickens, also refered to as cocks. Aspect spent many hours laboring over this finicky skip in pursuit of Critikal's money, to little avail.	2	https://clips.twitch.tv/ResilientLivelyOkapiJKanStyle-Pz426J_ripp-XoIr
Blindfolded Train	Multi-stream challenge to complete the final level of HITMAN: World of Assassination, completely blindfolded. Aspecticor was constantly barraged with TTS, harming his abilities to hear the game, his only tool of navigation.	2	https://clips.twitch.tv/ProtectivePuzzledFiddleheadsFUNgineer-6Zemn2SubTRwfWYo
Dragons Den	Canadian Shark Tank equivilant, origin of the occasionally used aspectiOhRly emote.	2	https://clips.twitch.tv/ObedientSlickScallionNomNom-hWixtbrsAy8P0o9u
violin skip	before the paris bomb launch became the meta in the SA/SO trilogy run, the paris run took about a minute. It involved the attic start, placing a remote bomb at a winch that releases a chandelier onto Viktor Novikov, then doing some distraction shots and running to the other side of the mansion, and using a violin or a bust to boost onto a chair then over the second-floor railing, where he would then pistol snipe Dalia Margolis and then leave via helicopter. Somehow, Aspecticor found that launching a C4 remote explosive with a breaching charge was easier than performing a simple violin skip, and has sworn off the attic start for the rest of his days.	2	https://clips.twitch.tv/NiceColdbloodedKeyboardCoolStoryBro-IQB8UoKxGxCzYpur
first viral LSF clip	When he first got his master Trilogy SA/SO world record, Aspecticor was basically on top of the world. A clip of him (clipped by a certain mod) became super viral on r/livestreamfail, so he had his 15 minutes of fame with the big shots at Twitch. His subsequent world records have been nowhere as viral, which perhaps explains why he doesn't seem to go hard for world records anymore PepeLa	2	https://clips.twitch.tv/JollyLuckyMelonRuleFive-hYU_yQIOLU1-uhuO
smurfspecticor	His camera glitched and showed his real skin color, he had to turn on color correcting lights to appear as a pale ass Canadian	2	https://clips.twitch.tv/HelplessFamousGrouseAsianGlow-8fmUe9xbi_0JhOYD
Contract Competition	Surely the video will be done soon Clueless	2	https://clips.twitch.tv/HeadstrongAmazonianCatVoteYea-hzea009-D3DayoMh
Berlin knife incident	In classic Chokespecticor fashion, Aspecticor threw a run on Berlin. This most infamous incident involved picking up a throwing knife instead of the nearby propane canister and throwing it at a non-target guard, ripping the run instantly.	2	https://clips.twitch.tv/GrotesqueDoubtfulStarlingNotLikeThis-M8WVYzkaGeKUKeuo
Marbie Mondays	More exciting than the average Raptors game.	2	https://clips.twitch.tv/GoodObliviousAyeayeArgieB8-iSSQAJKGMLgiJ4lz
aspect spilling stuff	what a clumsy guy ICANT	2	https://clips.twitch.tv/CaringDullFlyPeteZaroll-y1kFSZ_7Hz-a8DXR
Flavortown & Bi Fieri	"They make a porchetta that you won't forgetta."	2	https://clips.twitch.tv/BlatantCulturedClintMrDestructoid-44Rx6NLFt6n-JEee
Frogfoolery	Whilst attempting to catch a frog in Whittleton Creek, chat began to spam "Frogfoolery", an emote which did not exist and was not enabled on the channel. Aspect doubted its existence, but he cannot see new emotes until he refreshes his overlay, so he couldn't be certain. By the time he refreshed the overlay, Frogfoolery had been covertly created and added to the channel, ensuring he would never find out that he was being epicly trolled.	2	https://cdn.7tv.app/emote/641bcce83f88c5f0b4456452/4x.webp
fadedthanahokkaido	This emote is inspired by damianluck925's famous catchphrase, faded than a hoe, but he is replaced with Hokkaido target Erich Soders. The arms in the emote belong to MokshaMan, but color corrected to be more pale (he promises he touches grass)	2	https://cdn.7tv.app/emote/63773c5036012d401970a94c/4x.webp
Peneloupe	Everyone knows that Penelope as in Penelope Graves, the target in Colorado, is pronounced /pənɛ́ləpɪj/, not "Peneloupe," rhymes with canteloupe. Everyone but this resident Canadian, who proceeded to blame his Canadian education. What a melon.	2	https://i.imgur.com/y27fmNL.png
first chatter asking for feet	Aspecticor often recounts a story from his early days streaming, when he would stream and talk to an audience of no one. One day, a chat message finally came in, and it was asking him to show feet. Because he's such a professional streamer, he didn't even know how to ban them, so he was resorted to saying "please go away" in the most Canadian fashion. That chatter? Jhortplays	2	https://cdn.7tv.app/emote/63e982c8eba39cf380d78ac7/4x.avif
Moses Lee SWOONER	Look at this hunk, you would swoon after him too. He's the only thing that would keep you going while watching the Miami cutscene over again, just because SOMEONE missed their shots Lamonting	2	https://i.imgur.com/2SB7Msi.png
Red Suit	Aspecticor's classic speedrunner suit. not as exciting as say, the clown suit or the cowboy outfit, but acceptable. 	2	https://static-cdn.jtvnw.net/emoticons/v2/emotesv2_b22dce2ea2be487595ef8329d01cb4ee/default/dark/3.0
Good Kid	An indie rock musician who Aspecticor frequently plays songs from on stream, particularly their debut	2	https://www.youtube.com/watch?v=tjmk0C64eJg&list=PL8hyRqs__Q8DMFkjpddkBBpgrPCBdoE5V&index=28&pp=iAQB8AUB
Many Men	Early on, Aspecticor showed their utter disdain for the copyright law that keeps our society up and running, playing Many Men over runs of Paris. In an act of karmic justice, he almost never made it out of Paris.	2	https://www.youtube.com/watch?v=5D3crqpClPY&pp=ygUIbWFueSBtZW4%3D
watering his plants (allegedly)	look at his face, there's no shot this man watered the plant	2	https://twitter.com/aspecticor/status/1518371854162927616
ButterfieldCup	Co-winner of the Butterfield Cup of Musical Theatre (and the captain of Whittle House!)	2	https://www.youtube.com/watch?v=St1crxwRmis
AnEmoteAspecticorWillNeverComprehendForItIsSoComplexAndSoRuthlessInItsBeauty 	i̴̠͓̦̒͒͠͠f̸̡͑̀͝ ̴̡͔̲͊͛y̷̱̣̮̽͒̓͘͝ö̷̲̬́u̶̼̐ ̴̼̝̆͝g̷̲̯̘͌̂a̸͙͇͉͑z̶̠͙̩̙̝̓̈́e̶͎̥̎̂͝ ̸̙̇̉i̸̝̖̊͌̽̊̕͜ǹ̶̜͙̙̔t̷̛̮̬̃͒̀̊o̷͍̊̋͊ ̷̬͔̞̎t̸̺́h̴̗̞̰̄̂̏̏͜e̸͚͗ ̸̤̣̲̙́͑͜å̶͕͛ḇ̵̛͍̹̬̋̾̔ͅy̵̧̜͎̮̭͌̉̓͌s̵̢͉̳̩̀̈́s̶̯̋,̵̟͙̰̓ͅ ̶̭̲͌̉͐̇t̴̡̩̺̘͖̀̎̏̂ȟ̶̡̲͔̙̋͐͠ḛ̵̛̗͊̓̈́͠ ̵̠͚̼̩̎͋̑̅ä̸͈́͋̓b̸̠̰͈͗̌͛̋ẏ̶̢͖̈́̚͜͝͝s̵̨̨̥͂͐s̴̢͚̞͐ ̷̧̦͍͂̉̚ǵ̵̛̖̣͎̊́ͅa̴̢̲͍̖͒͘͜z̶͓̪̤̞̍͜e̴͓͚͍͛̓̌̀͝s̵͖̰̎̀͂ͅ ̵̪́̈́ȃ̴̡̎̄̃ḽ̵̗̳͍̪͋̋̏s̷̟̼̰̓̀̓ő̴͓̼̣ ̶̰̰̣̂i̴̥̟̪̤̤͌̈́̂̎̈́n̷̤̉t̸̖͐̏o̸̡̰̣̦͓̓͒ ̴̡͈̺̼͋͋͗ÿ̵̨̩͉̦́̈́̍͘͝ö̴̢́̿́u̷̼̎͗́.̶̰̖̱̗͈́̏́̚	2	https://cdn.7tv.app/emote/635f2bc1eadd44d30cee52a8/4x.webp
First partner app got denied	he gets ONE record and he thinks he's some kind of big shot that can waltz into there and get that partner badge NO SIR you gotta earn that shit	2	https://clips.twitch.tv/EphemeralAgreeableChowderBIRB-pUpg1G0J_bz_KYYP
brows	brows	2	https://cdn.7tv.app/emote/637202ae05d9d903f4ac1b81/4x.webp
PastyFacedEggheadInsideAMach3FighterJet	In the ICA Training Facility, an NPC refers to their plan as putting a "pasty faced egghead inside of a Mach 3 fighter jet". The emote depicts Aspect's face photoshopped onto an egg, photoshopped into a fighter jet. One cannot count even on all of their fingers and toes the various situations in which this emote is applicable.	2	https://cdn.7tv.app/emote/636dd3418fa7eca2aaf2c702/4x.webp
Nick Cage pillow	He's... he's right behind you!	2	https://www.uselessthingstobuy.com/wp-content/uploads/2019/04/Screen-Shot-2019-04-23-at-2.00.17-AM.png
September '08	Something that Aspect says quite a lot. It's a reference to The Other Guys, Aspect's favorite movie	2	
Getting wasted/sick at TwitchCon	He partied too hard and was bedridden in San Diego for like a week. It wouldn't be so bad if he enjoyed what San Diego had to offer, but instead he ate Denny's night and day while here smh	2	https://media.discordapp.net/attachments/864273305330909209/1028240066402857052/PXL_20221008_051507921.jpg?width=630&height=473
"this sniper plays Ave Maria"	Hey, hey so uh, hey chat, hey did you, hey did you know that uh, that this uh, this sniper, uh this, this sniper actually, uh, it uh, it plays, so it actually, it, it plays, uh-	2	https://clips.twitch.tv/AbstemiousSuspiciousCarabeefWutFace-Zv7uufhVKz_MbOhP
still hasn't cleaned pc	It's probably like Dune in that mf	2	https://terablitz.com/terablitz_media_01/dirty-pc-0000.png
Ken "The Dick" Morgan	Hehe guys you know what rhymes with "brick"? Wouldn't it be so funny if we replaced "The Brick" with "The Dick". Now let's say it a few thousand times until he gets it.	2	https://i.imgur.com/aviV5m2.png
Librarian story	Your librarian was crippled by the disease of alcholism and you're laughing? Like it's just some silly story? Despicable.	2	https://cdn.7tv.app/emote/63072162942ffb69e13d703f/4x.webp
The Other Guys	Aspect constantly references The Other Guys, and has admitted to watching the film more than 150 times, which is enough to have watched the film every month since the film released in 2010.	2	https://clips.twitch.tv/DignifiedBlindingLemurYouWHY-jWPLk_al7mosNrsS
vtuber	being a vtuber was one of the sub goals met in 2022, and it took a while for a model to eventually be made. with all that time and effort put in, surely he uses it more than once AYAYA	2	https://clips.twitch.tv/AntsyDrabPartridgeCeilingCat-c5eT6jDJ4CM5nZ52
lawn mowing sim collab with stanz	it's happening guys it's gonna be so sickkk	3	https://clips.twitch.tv/TiredSoftJuiceCharlieBitMe-Zq-xYHWnZveQQct7
FinniusJ	in S3K, NegNegTM is traditionally the leech that is the most forgotten about, and for a time was called FinniusJ after another person in the Atrioc community. As Aspecticor started to get more clout, he became a semi-official leech and assumed the position of most made fun of leech, being called FinniusJ then NegNeg.	3	https://www.youtube.com/watch?v=t6bZd_wg4k8
aspect77 emote prefix	Before changing his emote prefix to todays succint "aspecti" after partnership, it used to be aspect77. He changed it because he didn't want to be mistaken as an unpartnered brokie. 	3	https://cdn.discordapp.com/emojis/875224538399506522.webp?size=96&quality=lossless
Middle name is James	Andrew James Will. Three first names. Could it be any more white?	3	https://cdn.7tv.app/emote/60ca86d0f411fca3bb1a5a72/4x.avif
Glizzy Man	The first parody song that he made, and the first video of his of the Aspecticor brand. It was instantly one of the more recognizable leech songs, and he wouldn't be here today without it.	3	https://youtu.be/UZegxToGvtA
DougDoug GTA challenge	In his first ever Community Challenge, DougDoug challenged his community to complete a race in modded GTA 5 as fast as possible for $250 (with $100 for most stylish run). Because Aspecticor is a slowstander, he didn't win the cash prize, but he did get an honorable mention from DougDoug!	3	https://www.youtube.com/watch?v=pkyBOE-f9OM
Yo Mama Mondays	The Yo Mama Guy is the funniest person ever. Point blank and the period. I mean, have you seen his videos? What are you even doing here? Go watch Yo Mama Guy instead. With such classics as "Your Daddy so drunk, his breath gave you liver failure" and "Your Mama is like an NES cartridge; everyone in the neighborhood took turns blowing her, right in her butthole", Yo Mama Guy is a goliath of comedy with the cajones to make the jokes that Aspecticor won't. Tune in next Monday for more Yo Mama content live on stream!	3	https://clips.twitch.tv/ViscousOriginalTeaRedCoat-HX-S5sTHb8Ju53-J
Snussy	In December 2021, Aspecticor watched the entirety of Turbo live on stream. He kept repeatedly saying beforehand how this movie "bricked him up" as a kid, and wouldn't shut up about the red snail. Then while watching, he would loudly scream "AWOOOOOOOOOGAAAAAA" every time she appeared on screen. Following this, his audience started to parody him by pretending to be attracted to the red snail. Shortly after this, Snussy was added as a channel emote (type aspectiSnussy in chat), and even a song (now privated) was made to go along with it. Aspecticor would occasionally yell at chat demanding for them to post more Snussy in the chat. One time, when a new viewer asked why he was so aggressive about it, Aspecticor doxxed him live on stream and then called the SWAT team to his house claiming he had a bomb. This viewer was never seen again.	3	https://i.imgur.com/SWwiRc7.png
sahyj_	Promised an obscene amount of money to play contract during subathon, then called out Aspect for cheating (using HUD): "You fuck !"	3	https://i.imgur.com/rMvMZCA.png
Chatguessr	Aspect would sometimes use this site to play Geoguessr with chat, until he got rolled so many times he stopped to preserve the remnants of his ego	3	https://clips.twitch.tv/NimbleAverageHorseradishDeIlluminati-Gxi6bgTJzK3jHhmA
Turbo Friday	ITS TURBO FRIDAY BABYYYYYYYYYY THE TIME EVERY WEEK WHERE WE ALL ENJOY 1 HOUR AND 35 MINUTES OF CINEMATIC PERFECTION SURELY HE WILL DO IT THIS WEEK 	3	https://clips.twitch.tv/ManlySpunkySmoothieOneHand-sH8crokMDQxBbjm8
WIN ASPECT'S MONEY	Aspecticor's subathon rendition of the classic game show where he would give the promise of more and more money for a coin flip, only for it to be wrong and leave the gambler with nothing. Luckily, the viewers were more shrewd and we cleaned out his Paypal account (which is named AJW Capital Ltd by the way OMEGALUL).	3	https://clips.twitch.tv/CogentWimpyYakinikuDxCat-v5m0B3NUWlqvTAq9
we woke him up	In the middle of the subathon, Aspecticor had to wake up early in the morning to drive Katie somewhere. In a classic Aspecticor move, he didn't set an alarm or anything, so the mods resorted to playing loud videos in an attempt to wake him up. What finally got him up was Atrioc's popoff after completing Path of Pain in Hollow Knight, followed by the American Dad intro. The first thing he did, however, was turn down the volume and go right back to bed, putting all the effort in vain. Katie eventually woke him up.	3	https://clips.twitch.tv/CleverKathishPhoneTBCheesePull-p2GtJrC2RpDtv_qq
Red Carpet Bomber	When bomb launches were discovered to be a viable, consistent method for Paris speedruns, Aspect took to practicing. Initially, he would most often flub the trick, leading to the bomb not getting launched and instead blowing up on the red carpet. After a while, however, Aspect seemed to be getting some sadistic pleasure out of watching the fashion show goers screams of terror, and spent hours reloading and once again bombing them. This earned him the moniker of the "Red Carpet Bomber", and a spot of the FBI Most Wanted List.	3	https://clips.twitch.tv/ArborealFrozenJellyfishOSkomodo-U_wOQzluR_gUcwXH
Incredicore	After watching ΓÇöahemΓÇö playing the Incredibles on stream, a chatter made an emote of a random frame of Mr. Incredible with Aspect's face haphazardly plastered on top (pointed in the wrong direction). Chat instantly fell in love with this rootably terrible emote, even though some pointed out that the color contrast made it appear as if Mr. Incredible was wearing blackface, leading to its initial removal. It eventually received an update in which Aspect's face was blended in more smoothly. Still, it was ultimately removed (literally 1984).	3	https://cdn.7tv.app/emote/62ef6a802782bbb3954dc8fe/4x.webp
chatters named matty	mattyro1, MattySpice04, Mqttyy, MattyIce, MattyReay	3	https://i.imgur.com/Dayuot8.png
Soda Snail	Hey Aspecticor fans, You probably know the famous inside joke in the Aspecticor community that Aspecticor is a big fan of "Snussy". This, of course, is the pinnacle of comedy, and will be the magnum opus of humanity throughout its entire history on this planet. However, I would like you all to consider a new joke to make about Aspecticor. Perchance. Here is my idea for a joke: Aspecticor is a "Soda Snail". The joke here is that it's saying that Aspecticor really likes Soda, and Aspecticor is known for being slow explaining the "Snail" in it. Now, I don't know Aspecticor's actual opinions about Soda, but nevertheless, it could be funny to bring it up on stream. We can consider two outcomes of this joke: 1. Aspecticor is not a fan of the "Soda Snail" joke If Aspecticor does not like the joke, he will tell chat statements such as "no chat I am not a soda snail" and "what does that joke even mean?". By telling his chat that he doesn't like the joke, the chat will not follow his directions and keep repeating the "soda snail" joke to annoy him, generating more content. 2. Aspecticor is a fan of the "soda snail" joke If Aspecticor does like the joke, he will play into the bit, repeatedly calling himself the "Soda Snail". Chat will also play into the bit. I believe this joke has a lot of potential. Think of the things we could have by using this joke. We can have a "SodaSnail" emote, chatters can use this joke in their videos, and Atrioc has a new thing to call Aspecticor now! The #1 thing that we should do is repeat this joke nonstop for 1.5 years. I think doing that will be extremely beneficial to the Aspecticor community. Perchance. I hope you all consider this, and decide what's best for all of us.	3	https://clips.twitch.tv/SpotlessFitHedgehogSuperVinlin-KTTLNpVaRwOY-ogg
Dagger	On the (rare) occasion that Aspect hits a precise shot, he will often exclaim "Dagger!", which makes astoundingly little sense the more you think about it. Supposedly it's a basketball term or something, but do you really believe that Aspect watches basketball? cap	3	https://static-cdn.jtvnw.net/emoticons/v2/emotesv2_3088c5981444401da736d1c871116e74/default/dark/3.0
Ban/Unban Galliway	There used to be a redeemable channel point option that allowed one to ban Galliway if he was unbanned, and unban him if he was banned. Eventually Galliway was forgiven for his sins and released from this Sisyphean torture.	3	
Rocket League sub badges	Aspecticor used to be a big time rocket league head, being on the B team at Queen University's Rocket League club. However, he kinda fell off and so he changed his sub badges to shroomspecticor instead.	3	https://i.imgur.com/z9XEfC1.png
considered rebranding to spec	He was sick of all the people mispronouncing "Aspecticor" even though he really liked the name and its SEO	3	https://clips.twitch.tv/FuriousAgitatedHamsterM4xHeh-eiQOL2GEnIRMmNvw
Cars	KACHOW KACHUGGA 	3	https://youtube.com/shorts/NIWRMOehsDs
the aspecticor cardboard cutout	After winning an elusive target race against Atrioc, Aspecticor sent a cardboard cutout of himself to sit in the background of Atrioc's stream. Unfortunately for him, the background of his stream is kinda blurry, but it did get some use as a prop.	3	https://youtu.be/vH4MvTmylrc
clips channel	Before YouTube channels had dedicated shorts tabs, Aspecticor made a clips channel to explore short-form content. I mean you can type !clips and chat and subscribe to it if you want, I won't mind	3	https://www.youtube.com/watch?v=yG4nLfV4VRY
elusive target race against Atrioc and Linkus	what is an elusive target, you ask? An elusive target is the most entertaining way to play the Hitman game. When you play an elusive target there is only one time so when you play the elusive target there is only one way to win which is to defeat the target. After this, they never played elusive targets with him again, instead making a new challenge Hitman Horse to defeat him at	3	https://www.youtube.com/watch?v=RdOH1etdzv8
aspecticor.live	Optimal Viewing Experience, Moses Lee website	3	https://www.youtube.com/watch?v=HT3nrOQRJe0
icicle distraction	Such a terrible mistake to make in an on-pace run in one of the last cars in Train, surely he will never make that same mistake again	3	https://www.youtube.com/watch?v=fjyuzbA2kVE
Molotov Launch	Atrioc and Linkus hated Aspecticor for putting a molotov launch in his contract	3	https://www.youtube.com/watch?v=dGdHdoSpEvQ
bloon shanty	One of the last songs he ever made, he decided to sing an impromptu song on stream (in the tune of the Wellerman) about bloons. Atrioc immediately reacted to it, and soon other S3K members were adding their own lines.	3	https://www.youtube.com/watch?v=csU_k1-j-XE
Hitman Detective with Joats	Aspect and Joats would each think of a target, and the other person would have to guess the target using the same deductive strategies as in 20 Questions. You did have to leave the mission alive to win though, and Aspect did fail at that.	3	https://www.youtube.com/shorts/dIbqBLXkl-w
hitman anthology stream	Aspecticor is barely good at the Hitman: World of Assassination franchise, there's no chance he was able to finish any of the other games (except for Absolution, which barely counts as a Hitman game let's be real), although he put up a valiant effort during the subathon.	3	https://clips.twitch.tv/NurturingSassyRaccoonStoneLightning-HofMviDi4eX7LDYV
Shroomscientist tweet	Despite being written by an AI, this tweet managed to capture the essence of Shroomspecticor in his purest form. This was his peak, and no doubt the pressure to live up to the expectations that this Tweet set loom over him every time he hits send.	3	https://twitter.com/aspecticor/status/1491968730988879873
ViewBomb	ViewBomb is a state of the art, advanced AI Twitch view botting service and application, that offers faux viewership that extends further than a mere number displayed under a Twitch stream. ViewBomb allows for complete replication of a real, active, and normal Twitch chat. It also fakes Discord, YouTube, Twitter, TikTok, and Truth Social engagement.	3	https://i.imgur.com/hPWLY4M.png
Chef Marcello Ray	Chef Marcello Ray is head chef of Silvio Caruso and the biggest Sigma Male in all of Italy. He is known for his long-lasting feud with Sensation Johnathan Smythe and also for cooking the best spaghetti sauce in the world. Like how Johnathan is a confirmed Sensation, Chef Marcello Ray is a confirmed Sigma, as shown by the fact that he is a target in all levels of the Sigma Illusion escalation. 	3	https://i.imgur.com/cK4sCAJ.png
fooglie ass mf	Fooglie Ass Mf is a descriptor applied to Aspecticor in reference to a phenomenon known as "Fooglification". Fooglification is a multi-stage process during which Aspecticor transforms from his regular "un-fooglied" state into a "fooglie ass" state. Though Aspecticor has never been seen as a fooglie ass mf live on stream, it is known that he sometimes fakes bathroom, food, or Mercs/Katie breaks when he feels himself beginning the process (at which point Splive takes over). If you ever notice Aspect's skin turning a slight shade of blue and his ears elongating before a lengthy bathroom break, it is all but certain he is hiding his true nature as a fooglie ass mf off-screen.	3	https://i.imgur.com/3hNARC7.png
Soylent Splive	Soylent Splive is a strange character who rarely appears on Aspecticor's stream. Sometimes, when Aspecticor will excuse himself from stream, the room will flicker and change to that of Soylent Splive, a libertarian cowboy with an obsession for Soylent.	3	https://i.imgur.com/4ZibPei.png
Clueless WaterTime 48 hours	"48 Hours" or "Clueless WaterTime" refers to the fact that in 48 hours from now Aspecticor is going to unknowingly poison himself through the ingestion of water. Do not ask me how I know, why the back door was left slightly ajar, or why there are tracks in the snow that only lead into the house and not out. You might be asking can this be stopped? Unfortunately, it cannot. Like a meteor on a crash course towards Earth, the pieces have been set into motion and we can only watch in horror as they unfold. The only questions you should be asking yourself are how are you going to enjoy his presence in his last two days of life. Call him a boomer, call him Slurspecticor, live a little. As the Compound 1080 makes its way through his system, he is sure to remember the moments of simple fun you afforded him.	3	https://i.imgur.com/Xh8U3Bq.png
clock incident	Aware	3	https://preview.redd.it/5dconso04ng91.jpg?width=640&crop=smart&auto=webp&s=93ca8ca8d11faa43eb82651e31100aff7bf42f23
Finding Jesus	After losing a Mario 64 race, he was forced to watch this weird racist Christian fish movie AND its sequel.	3	https://media.discordapp.net/attachments/1121269962741399562/1123844722281164860/MV5BNjEzMDYxMTUtNzEwNS00YzJiLWEyY2MtOTA3MTk3OWFiNjhiXkEyXkFqcGdeQXVyMTEzMjQzMDM1.png?width=355&height=473
chat tierlists	Aspect ranked chatters in a tierlist at the very beginning of the subathon.	3	https://clips.twitch.tv/PiliableTalentedFlyNotLikeThis-5DeCh6Tc4GywXabP
type SpiderMan in chat	Ever had the thought that Aspecticor looked kinda like Tom Holland? This was back when he had hair and no dent, but KatieGrayx3 once deepfaked him onto Tom Holland as Spiderman. This is also why the partner emote is of purple spiderman	3	https://clips.twitch.tv/PerfectPluckyJuiceSmoocherZ-Gb_4wYqcmq4ZRrAh
Neon Ninja Suit	The Neon Ninja Suit is a suit introduced in HITMAN III as a reward for beating any contract in Tier 8 of the Elusive Target Arcade. The suit was notable for when it was used in maps like Sapienza's "The Icon" or Paris' "The Showstopper". The use of the suit in Aspecticor's stream has been cited in 204 cases of permanent blindness across the globe, and 1500+ partial eyesight loss in North America alone. The Canadian government has been heavily sanctioned by multiple countries for not immediately taking legal action against Aspecticor.	3	https://clips.twitch.tv/MistySecretivePheasantPraiseIt-b9YTjEcofyjbWqZy
trackmania streams	fu5ha and Nixolay (Wirtual's editor) got him into it POGGIES	3	https://clips.twitch.tv/LitigiousMistySkunkBabyRage-AQqBO-Mq39IQVDM6
Streamed for Evan during child's play subathon	During Evan Gao's mid-subathon vacation, Aspecticor filled in for a bit. He has the dubious distinction of having Child's Play lose money, which doesn't seem possible.	3	https://clips.twitch.tv/LitigiousFunStarlingCharlieBitMe-A1CvnCd5Kta0JI_J
hitman mod stream	playing with modified game files !!!! experimented with no/low gravity, npc following, airstrikes, and other nexus mods	3	https://clips.twitch.tv/EnticingEasyTofuTBTacoLeft-xc8LnaDFTi0ayjP_
Aspecticor Minecraft server	Minecraft Realm hosted by WadeWattsGunter. Featuring death counter wars, legal disputes, pixel art, and more.	3	https://i.imgur.com/leGy8Go.png
chat census	September 2022 chat survey from Cartwheel and Jhort	3	https://i.imgur.com/YbOjEtj.png
Kenya	kenya fit deez nuts in your mouth GOTTEM (PS this was a Moksha alt)	3	https://clips.twitch.tv/ObliqueCharmingTurtleHotPokket-JMocVs0DcajeuBKQ
Brian Tracy	Type !briantracy in chat!	3	https://youtu.be/obYIvQpMVPA?start=1073
S3K Podcast+	back when the S3K podcast was a thing and Aspecticor was still an up-and-coming leech	3	https://www.youtube.com/watch?v=TxbI7LWf4Mw
elden ring streams	Aspect did beat Tree Sentinel pretty fast tho	3	https://www.youtube.com/watch?v=GwJ36IxYB2U
thomas's interview with aspect	Audio got corrupted	3	https://twitter.com/ThomasOGremlin/status/1579346214797074432
Among Us with Stanz	The first time he ever played Among Us, even though his whole life he be acting sus	3	https://preview.redd.it/2cdh4w8rxv191.jpg?width=640&crop=smart&auto=webp&s=2e2cfe52725397caee8270127fade3921df38eb3
photoshop competition	"France" themed photoshop comp.	3	https://pbs.twimg.com/media/FUh3SaPVUAACEqW?format=jpg&name=medium
It Takes Two (with Udy)	Aspect and Udy make the best couple	3	https://clips.twitch.tv/UglyDeterminedAsparagusPanicVis-33jdFEDS2GBib9kL
Frogan's Get Out the Vote stream	Aspect was on a team with TheSerfsTV and JoshInJapan	3	https://clips.twitch.tv/SavoryImportantPangolinNinjaGrumpy-JvR0bt1NqxdBGfZt
turned Evan gay	Aspect is queering us and we are here for it slayyy	3	https://clips.twitch.tv/RepleteFriendlyWheelDxAbomb-p9kVVgdRLorsnN7k
valorant stream with fu5ha	VALORANT	3	https://clips.twitch.tv/OutstandingLongBisonKappaWealth-fhRuJd7_fizz7NRk
canon run	actually sitting down and playing the game, instead of metaphorically telling the projectionist to fast forward	3	https://clips.twitch.tv/MildObliqueDiscRedCoat-wL7wsrktsdGK11rG
osu stream	a bunch of his viewers and mods play osu so this was pretty fun, also the top player HappyStick dropped by too	3	https://clips.twitch.tv/HilariousFurryShrimpKevinTurtle-nt0jrcxsPltOIkTK
broken keyboard	Aspecticor has the bad habit of chewing his keyboard when he gets nervous	3	https://clips.twitch.tv/HedonisticCredulousHyenaAliens-kdHc47pzWCegDxWb
Bunny Suit	This was a sub goal that was fulfilled a long time ago, and curiously is the current donation goal...	3	https://clips.twitch.tv/FunFilthyAmazonDoggo-Rug0BKzxmM8t-qJH
Superliminal stream	ß┤┤ß╡ë╦í╦íß╡Æ ß╡É╩╕ Γü┐ß╡âß╡Éß╡ë ß╢ª╦ó ß┤░╩│ ß┤│╦íß╡ëΓü┐Γü┐ ß┤╛ß╢ªß╡ë╩│ß╢£ß╡ë	3	https://clips.twitch.tv/FrozenObliviousNigiriMVGame-LRrsCD3B5hZnexYS
content review with Avghans	you too can make a video that gets 1M views with his advice!	3	https://clips.twitch.tv/FlaccidVenomousAniseOSfrog-uwG774Hnnfyd5iMm
risk of rain stream with sykik and moblive	BOMBS AWAY	3	https://clips.twitch.tv/EndearingAdorableMarjoramKAPOW-iJJLNuPxpQaVfmKG
baba is you stream	but is aspect win	3	https://clips.twitch.tv/DignifiedUglyNarwhalDAESuppy-ML3h5eyKgyRDq22i
Metal Gear Rising: Revengeance streams	"spider mommy" HUH caught in 4k	3	https://clips.twitch.tv/CaringMildCodEleGiggle-ue9hFCOZrcSfpCBL
FussyBaby	During the Are You Smarter Than a 5th Grader stream, Aspect's character was named Fussy Baby, which the host delighted in repeatedly calling out	3	https://clips.twitch.tv/BetterVenomousScorpionPicoMause-7onkxZK6h-HEJeLj
sound alerts	used to be an integral part of the stream before they broke and never appeared again	3	https://clips.twitch.tv/AssiduousDeadCheetahPanicBasket-7zC6U-uaKfwJjBPE
presubathon 24 hour stream	24 hour stream during the launch of the Ambrose Island map.	3	https://clips.twitch.tv/AmericanBigBeanYouWHY-gkJKwgO1DWph5EdX
!mommy weird_ari, katiegray	spam !mommy in chat	3	
Playlist Creation streams	we used to have whole streams dedicated to finding DMCA-free music and still he chooses to fuck over the vod frogs	3	https://www.youtube.com/watch?v=-QtorATw7YM&list=PL8hyRqs__Q8AYhEwKGDHZ0IDT53ZkcHPQ&index=2&pp=iAQB8AUB
S3K reddit vids	years of being a theater boy has led up to him being able to act in reddit videos	3	https://www.youtube.com/watch?v=TbpbBbc_Kxc
Katie yelling at him for not paying the rent	Aspecticor almost got evicted and we would never get content from him again NOTPOGGERS	3	https://i.imgur.com/g4p249P.png
workout stream	I can't believe there are ZERO clips of shirtless aspect during his workout stream wtf	3	
vods channel	type !vods in the chat and subscribe guys	3	https://yt3.googleusercontent.com/TKyx3y0Iv6p0Jt5a3b1DFeapgV853OQyXAwHzncwEZwMgGseVlsQawVWXU7j3UHbxL7581Z5=s176-c-k-c0x00ffffff-no-rj
aspect ruined onteia's followage	he "needed to test an alert" sureeeee	3	https://i.imgur.com/Y9eiGJY.png
old/new POGGIES drama	"I miss the old POGGIES, straight from the 'Go POGGIES Chop up the soul POGGIES, set on his goals POGGIES I hate the new POGGIES, the giant boobs POGGIES The almost nude POGGIES, the jiggly lewd POGGIES" - KatieGrayx3	3	https://cdn.7tv.app/emote/612a18c98560641da72501fa/1x.avif
s1 record	he also did one blindfolded, but his pb was 4:39 before the molotov patch Sadge	3	https://www.youtube.com/watch?v=jV-AmFGSMqo
scripted fails on train	throwing for content	3	https://clips.twitch.tv/CorrectLachrymoseUdonUnSane-MQ1WyXUciTI_bL6N
Jhort paid for Aspect feet pic	everyone has a price, and for Aspecticor, that's 10000 bits	4	https://clips.twitch.tv/EnchantingHelpfulDogeBloodTrail-eKNjFHp8pBApOd6T
!minions	Atrioc was once sponsored by Minions: The Rise of Gru and there would be a !minions command that would spawn an overlay that would take over the stream if it was spammed enough. Even after the ad campaign was over and overlay removed, chatters continued to spam it even though it had no meaning. But in Aspecticor's chat, it does.	3	https://i.imgur.com/iTNGDCC.png
Shaqspecticor	Another emote like Incredicore, where Aspect's face was plopped unceremoniously on top of an image of Shaq dunking. It was eventually removed because of its limited application.	3	https://cdn.7tv.app/emote/630eb9103cfad7b708c47fb2/4x.png
PotFriend do this earl	Aspect, now's your chance to do it earl	3	https://cdn.7tv.app/emote/62927c1b6085d3df2595e1f4/4x.png
Aimlabs	Aimlabs is a software that is used by gamers to improve their aim. Due to Aspect's subpar aim (see: Misspecticor), he is often reminded that Aimlabs is in fact free.	3	https://youtu.be/dF71LZSEtVs
Roulette "Race"	He got destroyed by MattySpice...and AtomicGarbage...and Yannini...	3	
Sykik teaching Aspect	Sykik taught him Bangkok, and there's an alternate universe out there where Sykik got the world record and did hitman horse and all that	4	
Game of Squid	Isto is kinda a goat, just recreated Squid Game like that so fast	3	https://www.youtube.com/watch?v=QSn_in5YWcU
Sid from Toy Story	type AspectiSid in chat	3	https://cdn.7tv.app/emote/645c31b63123de30acc8b067/4x.webp
1v1 channel point redeem	Like the Water and Posture Check redeems, the 1v1 redeem was whisked away from our hands, like it was NOTHING, like WE were NOTHING. I'm starting to cry just thinking about them, I miss those redeems so much. He just got tired of losing and looking like a fool out of himself, I bet.	3	
smallant's one message	in response to "everyone is ahead of Atrioc" he sent "im ahead yeah"	4	https://i.imgur.com/krvyglZ.png
Aspecticor is an anagram for epic scrota	it's true (also an anagram of Arctic Peso, and Cope Racist)	3	https://i.imgur.com/GUE6bZt.png
AspectiShuffle	The AspectiShuffle emote depicts Aspecticor at The Streamer Awards dancing in the whitest way possible to a Yung Gravy performance.	3	https://cdn.discordapp.com/attachments/864273305330909209/1084324859380781176/ezgif.com-gif-maker2.gif
clint stevens	it's crazy that Clint Stevens just goes live on his alt Aspecticor instead of going live himself	3	https://clips.twitch.tv/SnappyCrowdedDotterelCoolStoryBro-TNJMMeZRp5RaA69j
Amazon Games Video	Aspecticor's chances at getting Partner were destroyed following this video being uploaded, until he paid a Twitch staff to backdoor into the mainframe and put him in the Partner list.	4	https://www.youtube.com/watch?v=haMHLg8VhyA
Jake from Accounting	just some random guy in new york who ruined his perfectly good speedrun	4	https://clips.twitch.tv/TameSarcasticTubersNotLikeThis-gLvdeYkFn8t3WjbN
Fox onesie	It always starts with a "no I'm not a furry" while wearing an onesie, then it ends with "owo *notices bulge*"' - alex73630	4	https://clips.twitch.tv/SpotlessRoundKittenNotLikeThis-bc9YfzMAGrBh0AkG
Gaybar	An old channel point reward used to be that if enough chatters spammed the GAY reward, it would progressively fill up the Gaybar until reaching 100%. Once that happened, Aspect would need to change outfits, either going shirtless or in a onesie. (peepoRiot NIPS OR I WALK) Trivia: OGs remember when it was just spamming !gay, and Twitch removed the redeem once so it was renamed GAI	4	https://clips.twitch.tv/ColdbloodedAggressiveMilkAMPTropPunch-D8V9jrcQBFRRE61Y
Rocket League streams	degen gaming	4	https://clips.twitch.tv/AlluringBenevolentLarkHeyGirl-Y0_-3OUsAuGMvKZD
Kaceytron stream	"Huh, I wonder what the chat is saying about me!"	4	https://cdn.discordapp.com/attachments/1121269962741399562/1121299273666019349/AT-cm7CdIbmfjPhvioC4_PCWGAAyw-preview-480x272.png
!safe	The Warlord is the twentieth Elusive Target Mission in HITMANΓäó and tasks you with eliminating Adeze Oijofor and retrieving maps and files detailing the target's network in West Africa. Unfortunately, Aspecticor has no map knowledge (because he is bad at game) so he couldn't find the safe, always being some number of floors above or below the actual floor. !safe used advanced computer vision to determine what floor Aspect was on and kindly guide him to the right one.	4	
SF wr holder	Got a lucky run (check his mod folders) and Atrioc challenged him (5:39 in the video) to repeat the run for $2500. In typical Aspecticor fashion, he choked.	4	https://youtu.be/OahFCpA3R5A
Atrioc tweets tierlist		4	https://www.youtube.com/watch?v=jmE3gUCFWUM
Mattyro RPS		4	https://www.youtube.com/watch?v=b87GSjk7-us
David Bateson video	David Bateson congratulated Aspect in his first world record!!! https://www.youtube.com/watch?v=-zthJ7F7bbI	4	https://clips.twitch.tv/HotAntediluvianYakAMPTropPunch-5nmwwiTq5ihEkfUt
Super Mario 64	On February 28th, Aspecticor returned to the world of Super Mario 64 Speedrunning and finally completed his first ever run. He clocked in a time of 1:31:13. This run placed him 1482nd on the leaderboard out of 1486 and cemented him as a bottom 10 all-time Super Mario 64 speedrunner. Additionally, this run was completed using save states, so not only was it as slow as molasses, it was also cheated. Were he not to have used save states, it quite possibly could have been the slowest 16-star run ever performed.	4	https://clips.twitch.tv/EnergeticTriangularTrayTwitchRPG-b9wLGF-AFuLW6Ap-
Old VFX/Blender Channel	Sublime CG -- The War Measures Act vid Hmmge why you so interested in the legal use of force Hmmge	4	https://www.youtube.com/watch?v=2bE9o3m9P5k
SASO race against BuffGuy	"just tuned in :) good luck in the race" On January 23rd, 2022, Aspecticor entered his first SA/SO race versus The_Buff_Guy. From the outset, it was a disaster in the making. Aspecticor, who uses Peacock (which was banned in the tournament), had no mastery on many maps. This included the final map of the race, Hokkaido, which required maximum mastery in order to smuggle in items. Additionally, Aspecticor only had routes for the first 3 maps. At the outset, it was pure disaster. In Paris, the most planned out of all of the maps, he spent 10 minutes resetting before getting out. This included one reset where, instead of closing a door and knocking out target Victor Novikov from behind, he simply threw the fish directly at his head. However, he was still in the running. What truly takes this race from event to "incident" is the Sapienza Disaster. Aspecticor did not have the correct sniper rifle for his intended route and instead opted to take The Majestic, a gun with a reload time longer than Slurspecticor's history of questionable statements. He then proceeded to have a full mental breakdown over the next 40 minutes as he continually failed his Sapienza route. In the meantime, The_Buff_Guy had completed Sapienza, Marrakesh, Bangkok, Colorado, and Hokkaido. Aspecticor was only put out of his misery when The_Buff_Guy finished his final map, cementing Asspecticor not only as a bottom 10 Mario 64 speedrunner, but also one of the worst SA/SO roulette racers ever seen.	4	https://i.imgur.com/4LQpF8b_d.webp?maxwidth=760&fidelity=grand
shroomstablishment	The Shroomstablishment is a term that refers to a group of chatters has rose to prominence in the Aspecticor community. Aspecticor claims that he is not a part of the organization and he has even claimed that the organization does not exist but its influence runs deep in the stream.	4	https://i.imgur.com/3yPe63k.png
Cookie (aspect's former cat)	fat	4	https://pbs.twimg.com/media/E6iHVq4UUAY96Gt?format=jpg&name=large
Congrats video	Evan made him cry (CryAboutIt) This and the David Bateson video, the community really went all out on it	4	https://clips.twitch.tv/UgliestDependableSandstormRlyTho-XWFBUNdRVCZLIE0L
Tucker tweet	Infamously, Aspecticor tweeted on March 18, 2022 that he "would love to smoke a bowl with @TuckerCarlson and pick his brain about that green m&m", referring to the now former (RIPBOZO) right-wing talk show host. In the above clip, a chatter first shares this line as a joke, but Aspecticor then steals it for his tweet. However, it is worth keeping in mind that Aspecticor is a known Tucker Carlson watcher and fan (being at January 6th, after all), so this sentiment most likely was unironic.	4	https://clips.twitch.tv/TriangularClumsyBeeNerfRedBlaster-Mk5c9Heylwy9Xipx
Onion Boy	You know, Vidalia Onions from this specific area in George are actually sweet because of the soil content, so you can eat them like an apple. Well, technically you can eat any onion like an apple, just like Aspecticor did, but next time he dies or fails a run he should consider importing some.	4	https://clips.twitch.tv/SullenPunchyVampirePicoMause-yw62UCQrHMGXR-LT
dhar mann copycat vid		4	https://youtu.be/t7RN8FpjLqw
Chasing Bloons (popathon)		4	https://youtu.be/Q-5OqOZut5E
Setup stream with Avghans	"They told me I was gonna burn my house down because I sent in a mock photo of my old computer torn apart I loved that stream lmao" -Galliway	4	https://youtu.be/pawP0uYfzR4
Unmodded and banned from Whodat's stream	He scammed believers when Whodat was playing Mario 64, aspect made an apology vid, whodat challenged him to watch Turbo to get unbanned	4	https://youtu.be/F_yWRbVqAdo
dhar mann vid	His only age-restricted video. What raunchy activities could he have been doing to end up like this?	4	https://youtu.be/9nPwfOIX4o4
Evident - Moistcritikal Rap	Moist raided him once during the Amok Runner craze, and he blew his chance to showcase the Moistcritikal rap SMH	4	https://youtu.be/90gXn4oiOZo
Bro v. Bro against PeyTheMusician		4	https://youtu.be/5vgExqkoIUs
Glizzy Conscience (feat. Syk1k_ and Evan_Gao)	"This just set rap back five years" -Atrioc. "Glizzy Conscience" is a parody of "Guilty Conscience" (Eminem, feat. Dr. Dre) that explores the inner dialogue (as Dr. Dre and Eminem, voiced by Aspecticor) of Atrioc in various situations, such as him taking a sip of water at an Atlanta bodega, paying Sykik after Fall Guys, and finding Evan_Gao in his home. Of note is that he left the Dee Barnes line, to which he feigned innocence by saying that he didn't know the reference.	4	https://youtu.be/1rio7IB6d-E
mental asylum	The Mental Asylum is Aspecticor's true place of residence, outside of his fanciful imaginations. The walls are scrawled with various phrases which appear often on his "stream", written in what appears to be blood. He also believes he lives with a cat and a girlfriend, though in reality he has seen no signs of other life in years. He was confined to the asylum following the Red Carpet Bomber Incident and has been trapped inside ever since. Recently, a journalist snuck into the asylum, and captured this exclusive footage, showing the depth of Aspecticor's depravity.	4	https://youtu.be/0W95-aQOdwk
inscryption	it's real fun but he played most of it offline Madge	4	https://www.youtube.com/watch?v=ZcLnWW1sIOQ
Hardest Flash Game Video	He never beat Euro Headers 2004, L bozo	4	https://www.youtube.com/watch?v=KFsht2L3iBI
sportskeeda article	after beating the Hitman SA/SO Master Trilogy World Record by one second, you know that Aspecticor was such a big deal. He even got an article written after him for this accomplishment: https://www.sportskeeda.com/esports/twitch-streamer-aspecticor-breaks-hitman-3-world-record-one-second	4	https://staticg.sportskeeda.com/editor/2022/02/54dc0-16443254933040-1920.jpg?width=710&height=473
Leech Olympics	the one with Linkus	4	https://clips.twitch.tv/SuspiciousWiseCheeseTheThing-Ci9Acsk_-rIUYQap
Leech Games	gaming	4	https://clips.twitch.tv/SassyCredulousFoxBloodTrail-eGJmbquAmCO3a2jZ
amazon streams	Aspect wasn't bi until chat made him buy the bi flag	4	https://clips.twitch.tv/PhilanthropicFragileMelonPeteZarollTie-jCeDzFX-rXBXoI8h
Mirror's Edge stream	He played it to remind him of his car part stealing lifestyle, jumping from building to building (a hospital and a hospital side building).	4	https://clips.twitch.tv/MotionlessTameLardPRChase-W4rH0M3ROKdzXVTB
halo infinite streams	why else would he have the halo helmet	4	https://clips.twitch.tv/MagnificentBrightManateeDancingBaby-dtNX4l4TghM1lVHo
Reddit Recaps	only the best content at r/aspecticor	4	https://clips.twitch.tv/ImportantHedonisticLapwingWow-iz88q9_V937piNNG
Katana Zero stream	Onteia bought the game for Aspect	4	https://clips.twitch.tv/BlightedSpinelessDragonfruitSeemsGood-fbZMVwWd7pX9uwK6
ALTF4	Not to be confused with Super Alt F4, the program that Aspecticor uses to close Hitman Freelancer whenever he fails (L bozo), ALTF4 is a rage-inducing game where a clumsy knight traverses traps. Aspecticor streamed this at the beginning of his career, and to this day has not completed it, recently giving the outburst "The creator of ALTF4 hasn't even completed the game, okay???" The background music, entitled "Round and Round," is said to trigger his PTSD to this day.	4	https://clips.twitch.tv/DependableBillowingSandwichCopyThis-s8UonpBJPYhUrzJ_
Pogostuck	someone check his pc	4	https://clips.twitch.tv/AssiduousStrongHorseBudStar-wy4z34qw__d0hwfi
Avghans Deal or No Deal with Evan	humor really is the social lubricant for the inevitable friction that is about to occur	4	https://clips.twitch.tv/AssiduousElegantKiwiPrimeMe-oNa3efvA6VW-e3IJ
anonymous gifter	An anonymous gifter gifted a sub to aspecticorslubedcheeks	4	https://i.imgur.com/1OzUl89.png
watch this ad stream	Aspect watched a bunch of viewer-submitted ads on stream	4	https://youtu.be/mCkg3ek0kHI
emote contest	Atlae made an amazing emote and aspect never used it	4	https://media.discordapp.net/attachments/947315324846497882/948030314817683496/aspectiGift.png
magic school bus	we're learning today PepoG	4	https://clips.twitch.tv/SneakyAmazingWitchKlappa-kkZT0SyzzUgp87Bg
Song of the Day	July 11th of last year was the last time Aspect posted a song. Arguably the more important annivesary.	5	https://media.discordapp.net/attachments/1121269962741399562/1128268515359608912/image.png
he peaked in september 2021	He never made a "best moments" video after September 2021, so clearly he hasn't had any best moments since September 2021. Fell off tbh	5	https://youtu.be/x9j9NNvqVf8
Qorn songs	"you know youve been around a while when you were here for the almost weekly qorn songs" - jhort, 10/02/2022; QornOnTheQob, otherwise known as Qorn, this chatter is known for their outstanding skills when it comes to digital music production, known for songs such as (the now privated) aspecitcor type beat.mp4. This chatter made a (now privated) fanreel to a remix to Tech N9ne's Faceoff, specifically the verse from Dwayne, 'The Rock', Johnson. The fanreel came to be because Aspecticor requested it to be 'like the one NegNeg has', which was Qorn's main inspiration behind this work of art. They also are credited with the origins of Fartmoor.	5	https://www.youtube.com/watch?v=p4JSZOlTIh8
blackjack stream	What would be an Aspecticor iceberg without some lost archival content? Well say no more, because "1426079700 720p60 1" will fulfill your needs. Camera pointed at his lap, will he or his chat bust first? Turns out, he's a terrible gambler and would never make it as a gambling streamer. Maybe that's why he scams the believers so much.	5	https://www.youtube.com/watch?v=D_JLKfj0x7c
doxxing luminnn	(no clip because obvious reasons) When Aspecticor was starting out, he was not good at streaming, to put it mildly. So much so that he straight up read out chatter luminnn's full legal name. Aspecticor was later sued for this breach of privacy, and lost 20 billion dollars in damages and legal fees.	5	https://i.imgur.com/1K5tZiE.png
Katie unVIPed	yes, aspect's girlfriend katiemac99	5	https://clips.twitch.tv/TameImpossibleVultureOptimizePrime-4vOvwKOoYhA2-WpJ
Elimidate		5	https://clips.twitch.tv/SassyFrailDonkeyChocolateRain-5BdnKbVW6mUrCx3Q
splitgate stream	literally ZERO clips of aspect playing this game (an era lost to time), so here's this clip instead. technically it's in the splitgate category	5	https://clips.twitch.tv/PhilanthropicFragileMelonPeteZarollTie-jCeDzFX-rXBXoI8h
Traffic from berniesanders.com	yes this actually happened	5	https://cdn.discordapp.com/attachments/864273305330909209/929297861189988392/BERNIE.png
Christmas album	"Why did you make a Christmas album" -Atrioc	5	https://youtube.com/playlist?list=PLxe5mQ3Kjk86bQKuAErttr-2i_2pIS4ji
Gamer Gauntlet	the old gameshow that he used to host, should make a comeback tbh	5	https://youtube.com/playlist?list=PL8hyRqs__Q8AWTEMtLcqjJEXkkrzmSDLH
Valedictorian Speech	Look at him, farming LULWs back in 2017. He was born to be a content creator	5	https://youtu.be/oPEU-93OAU8
One Handed Dark Souls	where he puttin that other hand huh	5	https://www.youtube.com/watch?v=RG8QWaEzB44
mattyspice trump memorabilia	In a video titled "Aspecticor Mod Application," MattySpice04 really pulls on the heartstrings of Aspecticor by empathisizing with him about their common Tucker Carlson watching, and commiserating about how the election was stolen. It makes you wonder why his mod application was denied, they have so much in common.	5	https://www.youtube.com/watch?v=iMyv4TMrSdA
monkey ball streams	they call him clutchspecticor for a reason, right	5	https://youtube.com/shorts/ISq_0dIJmAo
Asporkticor the Musical	the original aspecticor shanty	5	https://www.youtube.com/watch?v=ZG7DjR7IwHA
Afraid of slide whistles	THEVOICES	5	https://i.redd.it/duz2n63em6q71.png
original iceberg by Onteia	an iceberg on another iceberg? don't think too hard about it	5	https://media.discordapp.net/attachments/1121269962741399562/1127377904758706228/asoxo5q3of881.png?width=334&height=473
Resident Evil	if you were here for this stream, you were a real one	5	https://clips.twitch.tv/VenomousPoorVelociraptorBCWarrior-TCs3ijjKBCb4aVm0
LilUziDiagonal	2018 rl streams	5	https://clips.twitch.tv/NiceCuriousDinosaurPMSTwin
Anonymous Survey Confessions	In Aspecticor's attempt at branching out into variety content, he opened up a Google Forms anonymous confessional. Multiple responses were scapled by the DoJ, however due to the anonymous nature, nothing could be used against those accused.	5	https://clips.twitch.tv/FragileFrozenWheelFunRun-u7-ZVmPYLxblpeRG
bunnyga ted talk	was part of his mod application (now privated)	5	https://www.youtube.com/watch?v=d5cSkON9f48
Aspect as Evan's lawyer in Whodat case	Aspecticor the anti-labor anti-union lawyer advocated on behalf of Evan_Gao in Whodat court in a case against his editors	5	https://clips.twitch.tv/DarlingPluckyMangoThisIsSparta-5jM5Q0sQAHjEDHQ8
aspectiDance	the heart rate monitor shows that he's alive, the dancing shows that he's grooving. Onteia cut out the background of every frame by hand	3	https://cdn.betterttv.net/emote/6169d7a3054a252a431f36b4/3x
NA Aim	aspect, you know that aimlabs is free right?	0	https://clips.twitch.tv/GenerousLazyPeanutDxCat-N_u8F6mUy_V8JaRx
missing the Omega Strikers tourney	Aspect ignored an email for this tournament because he thought it was a scam, but in reality a lot of streamers were part of this event. Aspect really dropped the ball on this one. For shame!	3	
tevsthebowlgoblin	Aspect's IRL friend that pops into stream occasionally	4	
Water/Posture Check points rewards	some say that the removal of these rewards is Onteia's personal 9/11	1	
Aspect's housemate's nickname for him.	"Steve Gregory Alan Peterson"	2	https://clips.twitch.tv/TacitBumblingTomatoDBstyle-qDY_PrhGQJseJ3aN`;
